version: 0.1

phases:
  install:
    commands:
      - pip install -r requirements.txt -t app
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket cb-sam-test 
                                   --output-template-file compiled_template.yaml

artifacts:
  type: zip
  files:
    - compiled_template.yaml
